version: "3.9"
   
services:
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    env_file: 
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  game_server:
    build: .
    restart: always
    command: >
      sh -c "python manage.py makemigrations games &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:${GAME_SERVER_PORT}"
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - ${GAME_SERVER_PORT}:${GAME_SERVER_PORT}
    depends_on:
      - postgres
      
  redis:
    image: "redis:alpine"

volumes:
  postgres_data:

networks:
  default:
    name: grkrcn-global-network